### ISSUE TITLE
ReferenceError: [BABEL] 

### ISSUE THREAD

**Issue by jenyckee** [achydenius/rxjs-web-midi#1]
The example gives me ReferenceError: [BABEL] with node v 4.3.0

**Comment by achydenius** [comment]
I wasn't able to reproduce this. Can you copy paste the full error message?

**Comment by jenyckee** [comment]
> rxjs-web-midi@1.0.0 build:example /Users/jenyckee/sandbox/rxjs-web-midi-master
> browserify example/app.js -t babelify -o example/dist.js

ReferenceError: [BABEL] /Users/jenyckee/sandbox/rxjs-web-midi-master/example/app.js: Unknown option: /Users/jenyckee/sandbox/.babelrc.presets while parsing file: /Users/jenyckee/sandbox/rxjs-web-midi-master/example/app.js
    at Logger.error (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babelify._flush (/Users/jenyckee/sandbox/rxjs-web-midi-master/node_modules/babelify/index.js:28:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:example"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! rxjs-web-midi@1.0.0 build:example: `browserify example/app.js -t babelify -o example/dist.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rxjs-web-midi@1.0.0 build:example script 'browserify example/app.js -t babelify -o example/dist.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rxjs-web-midi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify example/app.js -t babelify -o example/dist.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rxjs-web-midi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rxjs-web-midi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jenyckee/sandbox/rxjs-web-midi-master/npm-debug.log
